[metadata]
name = fuzzmeter
version = 0.3.0
description = Fuzzing executor and measurer

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10
include_package_data = True
install_requires =
    flask
    jinja2>=3.1
    pandas>=2.0
    pyyaml>=6.0
    tqdm>=4.66

[options.entry_points]
console_scripts =
    fuzzmeter = fuzzmeter.cli:main

[options.package_data]
fuzzmeter =
    templates/*.html

[options.packages.find]
where = src
