[tox]
env_list = unit

[testenv:unit]
description = Run fuzzmeter unit tests.
base_python = python3
changedir = {toxinidir}
package = skip
deps =
    -e {toxinidir}
commands =
    python -m unittest discover -s tests
